version: 1

params:
  docker_tag:
    type: string
    description: The docker tag to use for the project
    default: ""

stages:
  build:
    - name: build
      type: command
      args:
        command: build
        params: 
          docker_tag: '{{ param "docker_tag" }}'


  default:
    - type: stage
      args:
        stage: build
